# Generated by Django 4.1.7 on 2023-03-02 05:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sum_order', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='ProductInOrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('id_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='order.ordermodel')),
                ('id_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='product.productmodel')),
            ],
            options={
                'verbose_name': 'Заказ в товаре',
                'verbose_name_plural': 'Заказы в товарах',
            },
        ),
    ]
